### ISSUE TITLE
Can you use GIF?

### ISSUE THREAD

**Issue by gitlab-stack** [Metabolix/HackBGRT#115]
See above↑

**Comment by EndrDragon44** [comment]
No, the bitmap is one of the only file types that are able to be loaded/executed in the "boot phase," or native mode. Additional software or even a complete modification of how the operating system itself is coded/made would be required in order to use a GIF file as the logo. It would not be possible to implement PNG files or JPEGs as it would require the same redevelopment of the OS like I aforementioned. A solution to be able to use GIF is if you developed a program that temporarily ran for a few seconds before any screen that shows up right after the real loading screen, like the fake loading screen that shows up when setting up Windows for the first time (See video[ here](https://user-images.githubusercontent.com/59771714/209875107-1ed66b52-cad0-4eec-9f34-b635a528b075.webm), I label the real and fake, notice how the logo disappears). If you were to code the feature of supporting gifs, center align everything, and add a gif of the spinning dots, boom! You made your own program. That is, if you know how to code. You could hire someone to make one that does, though. And to make the program run before everything right after the real boot screen would be something for someone else to explain/walk you through. 
I'll give you a link for a few programmers on Fiverr:
*Labels based on desc. / name of gig
 [All kinds of languages](https://www.fiverr.com/j_web_solutions/code-your-c-language-cpp-c-sharp-java-and-python-programming-tasks-projects)
[Desktop Program](url)
[Windows Program](url)
Please keep in mind that you would most likely need to code the program with the C Programming Language family (C, C++, C#). You can code with a mix of all three languages as they are all compatible with one another.

Hope this helps, even though I'm a month late!

**Comment by Metabolix** [comment]
Automatic file conversion during setup will be available in the next release.

**Comment by Metabolix** [comment]
Implemented in version 2.0.0.

**Comment by hiddensea** [comment]
> Implemented in version 2.0.0.

But how? Do I just put a PNG image in my HackBGRT EFI folder and it converts it?

**Comment by Metabolix** [comment]
In the new version the configuration is done before installation, so you can copy PNG or gif into the installer folder and use that filename (such as myimage.gif) in config.txt. It will then be converted during the installation. It is explained in the readme and in the config file.
