### ISSUE TITLE
Can't open windows

### ISSUE THREAD

**Issue by ZacLiiscool** [Metabolix/HackBGRT#124]
Plz for the love of god help me. I am a student and my computer stores everything that I need and the holiday season is coming to an end I can not just lose everything I had done plz help me.
the computer says failed to load config

**Comment by lol90101** [comment]
Use a computer to download a windows install image and flash it to a USB using Rufus (https://rufus.ie/downloads/) (Windows PCs only) or a multi-boot drag n drop ISO files Ventoy USB (https://www.ventoy.net/en/download.html) (Windows and Linux) and you can use repair your computer to open some diagnostic tools including startup repair and a command prompt. You might want to also enter your BIOS settings to configure the boot order (Windows Boot Manager 1st) if that's a needed thing. command prompt is useful because of the bootrec command. (also bcdedit). Hope all this info will help!

**Comment by Metabolix** [comment]
I'm sorry for your situation. The README does have a warning, though, and also a recommendation for creating a rescue disk before use. Version 2.0.0 should also have a working fallback to the original boot loader in case of errors.
