### ISSUE TITLE
EFI doesn't show up, also still normal Windows Logo

### ISSUE THREAD

**Issue by AbertTV** [Metabolix/HackBGRT#151]
secure boot and bitlocker are disabled.

 setup.log file with debugging enabled is attached. Can you help me?
 
 Thanks :)
[setup.log](https://github.com/Metabolix/HackBGRT/files/13178942/setup.log)

**Comment by Metabolix** [comment]
Thanks for the detailed log. Looks like the installation was successful and also the entry was correctly removed when uninstalling. Sometimes HackBGRT won't stay enabled unless you enter EFI setup ("BIOS") and manually move it as the default boot option. Can you reinstall and try that?

**Comment by AbertTV** [comment]
> Thanks for the detailed log. Looks like the installation was successful and also the entry was correctly removed when uninstalling. Sometimes HackBGRT won't stay enabled unless you enter EFI setup ("BIOS") and manually move it as the default boot option. Can you reinstall and try that?


I'm familiar with uefi und bios stuff. I allready looked at the bios and there was no extra option added. I only got one windows boot manager and that is the standard windows.

Let me know what else Information i can provide to help you figure out the issue.

Thanks.

**Comment by My1** [comment]
can you share some pics of your UEFI where the boot related options are?

maybe you can add one manually. also maybe you can check your EFI partition if the bgrt-related files are in there properly

**Comment by Metabolix** [comment]
What I would do is to check and update the boot entries in Linux (efibootmgr) or UEFI shell (bcfg). See [example](https://blog.stigok.com/2018/06/04/set-efi-boot-entries-uefi-shell.html). There should be an entry for `\EFI\HackBGRT\loader.efi` like the installer shows, and it should be the default entry to work. If this somehow still doesn't work, I would install a Linux boot loader and configure that to boot into HackBGRT without delay.

I am not a Windows expert so my options for Windows are a lot more limited.
1. Okay maybe you could find another tool to check the boot entries in Windows, but that is probably no use because it would most likely show exactly same things as the setup.
2. You could check your hard disk layout to determine if you have any suspicious extra partitions which might interfere with the setup (although bcdedit at least seems to be happy with the detected one).
3. You could try disabling fast boot (the suspend or hibernation thing) to make sure that you actually get a clean reboot. Strange how bcdedit uses the same GUID for HackBGRT and resume, that makes me suspicious although I don't know if it's really meaningful at all.
4. Lastly, you could also try the legacy install method (O). Make sure that you have some kind of rescue disk (Windows installation media or a bootable Linux or UEFI shell) available in that case.

**Comment by AbertTV** [comment]
Thanks for the replys!

That quickly turned into somthing i'm not that familiar anymore. I just tinkered a lot with msi boards wich this one also is. 

Will need to see when i find time for this, will comment again if needed :)

Thanks

**Comment by AbertTV** [comment]
I figured it out, works now. Thanks everyone for helping tho :D

**Comment by Metabolix** [comment]
Great. If you share your solution, maybe it helps someone else as well.
