### ISSUE TITLE
Linux-Surface Compat

### ISSUE THREAD

**Issue by Jacksery** [Metabolix/HackBGRT#154]
Hey there, I've got a surface pro 8 that I'm running Linux Mint on but still uses the Windows UEFI during booting so was wondering if there was a tool that'd work for me? thanks!

**Comment by Metabolix** [comment]
Most likely Windows is not involved in booting Linux Surface, so you should rather change the logo with a Linux-based solution such as plymouth. HackBGRT can't do any better.

If you really must, you can install HackBGRT manually from Linux. The basic steps are detailed in the readme. I don't provide any extra support or instructions for Linux because of the vast diversity of Linux configurations.
