### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by coco621** [Metabolix/HackBGRT#161]
hi, when starting up I have an error that appears, I have to press a button and my custom logo starts. I am attaching the photos, thank you for your work.
![20231130_153900](https://github.com/Metabolix/HackBGRT/assets/106428589/9885fb8f-8031-40b1-b81c-0c89a34d1e74)
![20231130_161426](https://github.com/Metabolix/HackBGRT/assets/106428589/bdd57876-cd31-4a69-936b-cc805f3f2f23)

**Comment by Metabolix** [comment]
Please run the installer again, select "show boot log" and then attach `setup.log` here.

**Comment by coco621** [comment]
[setup.log](https://github.com/Metabolix/HackBGRT/files/13515570/setup.log)

**Comment by coco621** [comment]
that's right?

**Comment by Metabolix** [comment]
Your first screenshot is from a very old version of HackBGRT. Also your log file has so many steps and reboots (even booting to firmware / UEFI setup) that I don't really know what you have done and at what point did you get these error messages.

Can you please run these very simple steps:
- R = remove completely
- delete `setup.log` to get a clean log
- I = install
- reboot
- L = show boot log
- if you still get any error messages, send the new `setup.log`, without any extra steps.
- if you don't see anything of HackBGRT when booting, you can repeat the test with each of the other install methods.

**Comment by Metabolix** [comment]
This log still does not look correct, it shows that you still had HackBGRT installed (not removed) and you enabled with the second option (J) not first (I). Also you did not delete the log, there's a part left from the previous day. It's impossible to help if you don't follow the steps. Also, from the log it looks like HackBGRT is working, so what kind of error do you now experience?

**Comment by coco621** [comment]
Good morning.  However, I deleted it with R and re-downloaded your zip.  in I this I do nothing.  no entry in the .log.  I have a message when starting up for 3/4 seconds and then the custom logo appears.

**Comment by Metabolix** [comment]
What message is that

**Comment by coco621** [comment]
![20231202_093035](https://github.com/Metabolix/HackBGRT/assets/106428589/3de3f615-b906-45cc-812e-810b115cdfcd)

**Comment by Metabolix** [comment]
Thank you! I've now located the source of your error message. It is caused by some extra data which `bcdedit.exe` always puts into the boot entry. The *shim* loader wrongly tries to use that as a path. There's a report in shim (https://github.com/rhboot/shim/issues/370) about this problem and I've sent a pull request (https://github.com/rhboot/shim/pull/621) to fix it, but it's out of my hands.

Meanwhile, you should use the `I` install option. You can also run the `I` option now without uninstalling first, and it may sometimes fix this issue. If it does nothing, you will need to provide more information (logs) about that. It apparently works for many people, so it's hard to believe it literally does nothing.

About your log, it clearly starts with date "2023-11-30 11:02" and then continues at "2021-12-01 23:28" when you tried the `J` option, so obviously it was not properly deleted between those times, and it makes me wonder if you really even tried the `I` option this time.

**Comment by Metabolix** [comment]
How do you mean ”does nothing”? What happens when you press `I`? What do you get in the log?

**Comment by coco621** [comment]
Yes, I just took the test again. but no custom logo.

**Comment by Metabolix** [comment]
It's 100% certain that `I` does something and produces a log unless you have done something very special to break it. So without this data I cannot help you any further.

**Comment by coco621** [comment]
I'm going to do it again just with the "I"

**Comment by coco621** [comment]
[setup.log](https://github.com/Metabolix/HackBGRT/files/13538718/setup.log)
here's just the "I", no error at startup but still the original logo.
