### ISSUE TITLE
Error while tryna uninstall (Windows 11 Insider build 23619.ni)

### ISSUE THREAD

**Issue by sidewayzz** [Metabolix/HackBGRT#171]
[setup.log](https://github.com/Metabolix/HackBGRT/files/13997572/setup.log)
Can't uninstall HACKbgrt

Steps-
1. Download HackBGRT-(2.1.0).zip and extract all files.
2. Start setup.
3. Select install
4. Does everything fine
5. Fails
6. Opens setup to uninstall
7. GIves error
8. Disabled for now

Log file is attached
OS - Windows 11 Insider build 23619.n

**Comment by Metabolix** [comment]
It says you cannot uninstall because HackBGRT doesn't exist. So it's not installed and you don't need to uninstall. I have now fixed this (commit 39596aa), so this error will not be visible in the next release. (However, I will not make a whole new release for this rather insignificant change.)

You have cut your log and I don't know what happens in your step `5. Fails`. What fails and how? If this is an issue, get the latest release (currently 2.4.0) and report the problem if it's still happening.
