### ISSUE TITLE
❌Windows won't start!!!

### ISSUE THREAD

**Issue by Andrew-Sor** [Metabolix/HackBGRT#185]
**What happens?**
 There is this error on startup. I have a recovery disk, but how can I restore the bootloader?

![WIN_20240410_22_03_09_Pro](https://github.com/Metabolix/HackBGRT/assets/133566800/847090e1-d0e1-4040-ae9d-bdc6323de4ed)

**How this happens?**
Explain exactly the steps you did:
1. Download HackBGRT-(version).zip and extract all files.
2. Start setup.
3. Install

**Log file**
Impossible

**Comment by Andrew-Sor** [comment]
I found the instructions myself on the Internet and corrected them

**Comment by Metabolix** [comment]
I don't get it, why do your people keep trying with 1.5.1 while the recent version is 2.4.0?

**Comment by Andrew-Sor** [comment]
> I don't get it, why do people keep trying with 1.5.1 while the recent version is 2.4.0?

Because it really works and replaces the logo. And the latest version had absolutely no effect on starting Windows. There is, of course, a small drawback that version 1.5.1 is not very stable and during installation, according to all the rules, you have to press a key to boot into Windows. But fortunately, after several installations we managed to do it well. But after that I would like to have a tool for opening access to the disk with the bootloader in order to replace splash.bmp there because when I installed it again to change splash.bmp, I got an unbootable PC...

**Comment by Metabolix** [comment]
I obviously do not accept any "bug reports" about the 8 years old version.

The recommended choice is to use the most recent version. If it doesn't seem to do anything (probably because some kind of antivirus or other safety measure prevents changing the default boot loader), do not uninstall it but go to the UEFI Setup and choose the correct boot entry manually.

If this is not possible for you (for example, your computer doesn't show the HackBGRT boot entry), there's still a better way for you: the installer has the legacy option which works pretty much like the legacy 1.5.1 version. There should be absolutely no need to use the old version.

And in any case, if you have installed a version which works for you, then of course you have to use the setup from that version to change the configuration.

If you mix different versions, it's totally going to break. Always use just one version.

**Comment by Andrew-Sor** [comment]
> probably because some kind of antivirus or other safety measure prevents changing the default boot loader

I don't have any third-party antiviruses, and "Secure Boot" is disabled...

> go to the UEFI Setup and choose the correct boot entry manually

And how to do this?

> If this is not possible for you (for example, your computer doesn't show the HackBGRT boot entry), there's still a better way for you: the installer has the legacy option which works pretty much like the legacy 1.5.1 version. There should be absolutely no need to use the old version.

I don't know, but this option also had no effect...

> And in any case, if you have installed a version which works for you, then of course you have to use the setup from that version to change the configuration.
> 
> If you mix different versions, it's totally going to break. Always use just one version.

I used one version, but for some reason the old logo came back and I decided to delete and install again, but then I accidentally deleted some file and it no longer wanted to be installed.
Every time I reinstall, I feel some difference in the effect (I don’t know what this is connected with), although I use the same version...

It seems to me that in my case, if it was installed correctly, then it is better not to touch anything except splash.bmp, but this requires access to the disk with the bootloader without repeating the installation process

**Comment by Metabolix** [comment]
> I don't have any third-party antiviruses, and "Secure Boot" is disabled...

Looks like sometimes Windows restores the boot loader (or rather, BootOrder) by itself.

> > go to the UEFI Setup and choose the correct boot entry manually
> 
> And how to do this?

UEFI Setup is what people still tend to call BIOS. The setup.exe has an option for this, or you can search instructions based on your computer. Usually you can get there by pressing F2, F11, F12 or Delete right when you power on your computer, depending on your computer. How to navigate and change the settings depends on your computer.

> I don't know, but this [legacy] option also had no effect...

Feel free to show the log again. (You can first remove the old log to avoid unnecessary old info).

> Every time I reinstall, I feel some difference in the effect

Shouldn't be any...

> It seems to me that in my case, if it was installed correctly, then it is better not to touch anything except splash.bmp, but this requires access to the disk with the bootloader without repeating the installation process

That's why the current version has an option for just copying files. I hope we get it working for you.

**Comment by Andrew-Sor** [comment]
> Looks like sometimes Windows restores the boot loader (or rather, BootOrder) by itself.

I don't know.

> UEFI Setup is what people still tend to call BIOS.

Strange, I didn’t find a choice of boot entries in the BIOS... I’ll look on the Internet.

> Feel free to show the log again. (You can first remove the old log to avoid unnecessary old info).

Okey.

> Shouldn't be any...

I don't know, but it is so...

> That's why the current version has an option for just copying files.

Yes, but the installation process itself is complicated. The old version does not need a certificate or anything else. But perhaps you can install the old version and change the files using the new one?

**Comment by Metabolix** [comment]
> Yes, but the installation process itself is complicated. The old version does not need a certificate or anything else.

The old process required disabling Secure Boot. There's a trade-off.

The most legacy-like configuration can be installed with command prompt: `setup.exe install skip-shim install enable-overwrite`. (I will also fix `skip-shim` in next version so that you can omit the first `install` there and avoid copying some unused files.) This option will not be available in the menu because I want to minimize the number of bug reports about non-bootable computers.

If even this doesn't work, then I would be very interested to know if version 1.5.1 truly still works.

> But perhaps you can install the old version and change the files using the new one?

You could do that, and you actually did that according to your first screen shot, but your setup broke because you had the new config options which are not compatible with the old loader.

**Comment by Andrew-Sor** [comment]
> The old process required disabling Secure Boot.

Well, I have it turned off, and I didn’t turn it off, it was already turned off...

> The most legacy-like configuration can be installed with command prompt: `setup.exe install skip-shim install enable-overwrite`.

Ok I'll try to install the latest version this way.

> I would be very interested to know if version 1.5.1 truly still works.

Yes, it really works, but the bootloader broke because I deleted the files, and it didn’t want to be reinstalled so that they could be restored...

**Comment by Andrew-Sor** [comment]
> The most legacy-like configuration can be installed with command prompt: `setup.exe install skip-shim install enable-overwrite`.

How can I change splash.bmp after such an installation?

**Comment by Metabolix** [comment]
You can first edit the image and then use the same command to re-install (or more simply `setup.exe skip-shim install`).

**Comment by Andrew-Sor** [comment]
Okey, thanks

**Comment by Andrew-Sor** [comment]
Thanks a lot! Now everything works great! Let's see if anything changes after re-installing to change the logo...

**Comment by Andrew-Sor** [comment]
Yes, I reinstalled it a few more times to adjust the logo and everything is fine. Thank you very much!!!

**Comment by Metabolix** [comment]
You're welcome.
