### ISSUE TITLE
stuck at boot screen

### ISSUE THREAD

**Issue by tloc241** [Metabolix/HackBGRT#187]
after motheboard logo show up, it switch to windows logo and get stuck there. its manage to get back to stock normally, but i ran it 2 more time and it still have the same problem (even with J opttion)
here is the log  file: 
[setup.log](https://github.com/Metabolix/HackBGRT/files/14961384/setup.log)

note: i do dual boot 2 different version of windows, maybe this cause something?

**Comment by Metabolix** [comment]
I don't fully understand your report.

I have encountered a similar situation where Windows boots very slowly (appears to be stuck but continues finally). It happened to me a few times on the same computers which usually work just fine, and it got better on the next boot. It's hard to say what connection it has to HackBGRT and if there's any possible fix. (Note that HackBGRT is not running anymore at that point, so the slowness is something that Windows does.) I would advise you to reinstall (with `I`) and reboot at least a few times very patiently to see if it gets better.

Your first try (with `I`) looks ok, there's proper boot log which says HackBGRT was used and working.

Your later tries (with `J`) look like HackBGRT was not run during boot. This is a common problem with that install method, Windows seems to restore the old boot sequence and skip HackBGRT. That's why it's the second alternative.

I don't multiboot Windows, so I can't say what effect that might have.

**Comment by tloc241** [comment]
@Metabolix i have cap an image of boot screen with I option here
![IMG_20240412_234615_169](https://github.com/Metabolix/HackBGRT/assets/112869206/c8238336-991c-43f3-9f5b-8c6460ecd508)
it got too this and freeze (i have wait 5 min but nothing happen on screen), even after reboot two time (like i said above) 
weird

**Comment by Metabolix** [comment]
Yes, it took ages to boot for me too (probably 10–20 minutes) but finally it started working normally again. I'm not sure anymore if I changed the image during the process. Now it doesn't happen anymore so I can't even reasonably investigate it.

When the custom logo shows, your computer is already running the Windows boot loader. Whatever makes it so slow is a Windows thing. Maybe it's some obscure compability problem with the image file (a specific size or something). You could try another image with different dimensions or try either `image=remove` or `image=black` in config.

It's an interesting problem. If you get it working with some settings, please retry with that exact image and share exact details about what works and what doesn't.

**Comment by tloc241** [comment]
@Metabolix thank for ur response, i will try it again and share it back here when i have time <3
