### ISSUE TITLE
could not load splash.bmp

### ISSUE THREAD

**Issue by Kosemii** [Metabolix/HackBGRT#23]
When installing without debug=1, the error message is simply "could not load splash.bmp
fix your bootloader"
but with debug=1 it's quite hard to find the issue, any ideas? 
![Image of debug](https://user-images.githubusercontent.com/22931076/41997732-c390fb14-7a50-11e8-8b4d-3f417786db54.jpg)

**Comment by Metabolix** [comment]
I'm confused. The debug output shows "Loading \EFI\HackBGRT\splash.bmp" succeeding, so everything should be fine. Can you please just double-check without debug=1?

**Comment by Kosemii** [comment]
I've tried multiple times without debug=1,
all end in "failed to load splash.bmp"
even while using debug=1 when pressing enter to continue boot, it fails to
load splash.bmp

**Comment by Metabolix** [comment]
Looks like you have installed HackBGRT wrong. I noticed now that you have `EFI\Microsoft\Boot\bootmgfw.efi` as the boot path in your config. If you are using another boot loader (e.g. GRUB) to load HackBGRT, you should choose D(isable) from HackBGRT setup in Windows (see README). Otherwise, if you only use Windows, you should have `boot=\EFI\HackBGRT\bootmgfw-original.efi` as your boot path at all.

**Comment by Kosemii** [comment]
Oh yeah, that fixed it haha, thanks man
