### ISSUE TITLE
Squished Aspect Ratio

### ISSUE THREAD

**Issue by thomastthai** [Metabolix/HackBGRT#31]
I created an image that's 256x128 pixels. The logo was composed of mainly a big circle. When booting up, it's squished in the vertical or expanded in the horizontal. 

These different settings in config.txt were used: resolution: 0x0, -1x-1 and 256x128. None of them produce the image with the proper aspect ratio for the circle logo.

I've tried splash.bmp images with larger dimensions like 600x600 and the default Windows logo showed instead.

What is the max resolution for the splash.bmp image?

**Comment by thomastthai** [comment]
GPU graphic card is AMD Radeon WX 9100 with ViewSonic VP3268-4K monitor. 

Since the graphic card driver isn't loaded yet during boot, it uses the default resolution.

I drew a circle in the included splash.bmp image and the aspect ratio is also distorted during boot up.

**Comment by thomastthai** [comment]
My normal desktop screen resolution is 3840x2160. I drew the logo in that resolution.

It turned out the boot-up screen resolution had an aspect ratio of 4:3. I changed my screen size to 1200x900 and scaled my image until the circle was not squished. Ran HackBGRT again and installed the 4:3 aspect ratio image. When it boot up, it looked right.

Images with size greater than 256 pixels in width or 128 pixels in height wouldn't get shown. Instead, the default Windows logo was shown. The default Windows logo looked much bigger than those maximum dimensions though.

I hope this helped someone.

**Comment by Metabolix** [comment]
The resolution in config.txt is screen resolution, not image resolution. So 256x128 is clearly not correct.

Many computers don't use the correct video drivers during boot, so the available resolutions will be very limited. The resolution is often something like 800x600 or 1024x768. You can try to set a resolution with better aspect ratio in your config.txt, for example 800x480 or 1024x600. If they don't work, your best choice is to squish your image the other way so that it looks right during boot.

I don't know if there's a specific limit for the image size. My laptop seems to use 800x600 resolution during boot, and a 1024x768 image works fine but 1366x768 doesn't. You will just have to try different image sizes. As you noticed, usually you will get the Windows logo if your image is not supported.

There's really nothing I can do about either of these, because my software only loads the image and it's up to Windows to show it or not, so I'm closing this report.

**Comment by Privat-Paula** [comment]
guten Abend alle zusammen ich hätte gerne mal gewusst wie das richtige Auflösungs Verhältnis ist bei (HackBGRT) um das Windows boot-logo bzw Bild 1 zu 1 zu tauchen mit einem anderen Bild /danke

**Comment by Privat-Paula** [comment]
wäre sehr wichtig danke
