### ISSUE TITLE
Boot image restores to windows logo after macOS software update

### ISSUE THREAD

**Issue by rahwinside** [Metabolix/HackBGRT#45]
Hi,
  I am using HackBGRT to change the bootlogo of my Windows Server 2016 installation on my MacBook Pro 2016. Whenever macOS gets a software update, the boot logo in Windows restores back to the default one.
I have checked it HackBGRT folder and tried to rerun the tool. The image hasn't changed in HackBGRT... there is a culprit elsewhere.

**Comment by Metabolix** [comment]
It's because HackBGRT replaces the default Windows boot loader and the update "fixes" this by restoring the original one. Currently there's no builtin solution for this, but you can create a persistent boot entry for HackBGRT with some other tool, as described in the README / Multi-boot configurations.

**Comment by Metabolix** [comment]
Please try the new release which can create a proper EFI boot entry. I can't offer any support with configuring the Mac boot loader, so you need to turn to the Mac community for that. The only other option is to automatically re-enable HackBGRT after each update (`setup.exe batch enable-overwrite`), which is also now possible although needs to be manually set up.
