### ISSUE TITLE
Issue... 

### ISSUE THREAD

**Issue by ReddyCorr** [Metabolix/HackBGRT#47]
Windows Pack: 1809

Problem: "EFI System Partition was not found.
Press enter to exit, or give ESP path here:"

I can't solve it, I searched for answers everywhere. Please, help me.

**Comment by Metabolix** [comment]
Looks like your computer does not have EFI, so this software will by definition not work for you.

**Comment by ChenXiaoming233** [comment]
Hello, I have encountered the same "EFI System Partition was not found." issue, but apparently my computer boots with UEFI, because the disk partition table is in GPT format, which can only be booted by UEFI. It's worth mentioning that I used a wintogo made from a vhdx virtual disk as the system disk, so I'm not sure what impact this approach may have caused.

**Comment by Metabolix** [comment]
If you wish to investigate it further, you could check if you can find the partition with `diskmgmt.msc` or with `diskpart` command-line tool and if you somehow can mount it with `mountvol A: /S` or some other command. If there's some feasible way to access it, I'd be happy to hear about it.
