### ISSUE TITLE
Recovery after deleted the \EFI\HackBGRT folder

### ISSUE THREAD

**Issue by bjwdttz** [Metabolix/HackBGRT#50]
I have installed the HackBGRT by setup.exe, and deleted the \EFI\HackBGRT folder. Could you please help me to recover the efi settings?
This computer installed both Win10 and Linux, booted by grub. (Now Linux worked normally)

**Comment by bjwdttz** [comment]
Solved.  Basically using this method: https://github.com/Metabolix/HackBGRT/issues/34#issuecomment-473568959
But I used DISKPART command to assign the letter to EFI partition first.
After Win10 worked normally, I installed the Linux image disk and repaired the Linux boot files.

**Comment by Metabolix** [comment]
With current version (1.5), if you delete HackBGRT folder, you need to manually recover \EFI\Microsoft\Boot\bootmgfw.efi, which is replaced with HackBGRT. You can either use Windows recovery tools or download the file from somewhere.

The real fix for HackBGRT would be to create a new boot entry instead of just messing with the files. We'll have to see if this happens some day. ;)

**Comment by Fred583** [comment]
I know this is old, but how do you recover that file?

**Comment by bjwdttz** [comment]
@Fred583 I am exactly using the method the link provided:  https://github.com/Metabolix/HackBGRT/issues/34#issuecomment-473568959 , this is about to format the windows bootmanager, and build a new one.
And, as the author said, you can download one from the internet.
