### ISSUE TITLE
Signing EFI

### ISSUE THREAD

**Issue by Leif-US** [Metabolix/HackBGRT#55]
Does anyone know a way to sign this application? On Surfaces disabeling secure boot triggers an annoying red screen, so I would be really happy if someone could help with signing this great software. Greetings

**Comment by sylveon** [comment]
From Linux, use `sbsign`, from Windows use `signtool`. You will need to generate and enroll your own secure boot certificate however.

Alternatively, @Metabolix might want to try using https://github.com/rhboot/shim-review/ (it's not a shim but I guess it might pass).

Otherwise, it involves getting an EV: https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/lsa-and-uefi-file-signing

**Comment by Leif-US** [comment]
Thank you very much!

**Comment by S1m1B1lly** [comment]
Oh man im so confused im having the same problem do you know how to fix?
im using surface pro 4
and i dont really know those EFI Stuff and commands i dont really know how to do this.
can someoeone give me a help?

**Comment by RecklessRascull** [comment]
@S1m1B1lly might just be me, but I’d assume that you should maybe not be messing around with this tuff if you don’t understand it. You can mess up your PC quite badly.

**Comment by Metabolix** [comment]
Version 2.2.0 includes a signed shim from Debian to support Secure Boot.
