### ISSUE TITLE
I modded Support PNG and JPEG format image file . But I have problem .

### ISSUE THREAD

**Issue by FREEWING-JP** [Metabolix/HackBGRT#63]
Hello !
I modded HackBGRT to support PNG format image file using upng library .
https://github.com/FREEWING-JP/HackBGRT/tree/test/add_upng

But Ihave problem .
* Build only the 64-bit version . 
  Because I don't know how to write a Makefile script .  
* This modify is TRUE SAFE ?
  I don't know it has any MEMORY LEAK or/and STORAGE FILE BREAK .

<img src="https://raw.githubusercontent.com/FREEWING-JP/HackBGRT/test/add_upng/upng.jpg" alt="Support PNG format image file using upng library ." title="Support PNG format image file using upng library ." width="320" height="240">

**Comment by FREEWING-JP** [comment]
Hello !
I add support JPEG format image file using picojpeg library .
https://github.com/FREEWING-JP/HackBGRT/tree/test/add_picojpeg

But still I have problem .
* This modify is TRUE SAFE ?

<img src="https://raw.githubusercontent.com/FREEWING-JP/HackBGRT/test/add_picojpeg/HackBGRT_MULTI_1280px-Burosch_Blue-only_Test_pattern_mit_erklaerung.jpg" alt="HackBGRT_MULTI Support JPEG format image file using picojpeg library ." title="HackBGRT_MULTI Support JPEG format image file using picojpeg library ." width="320" height="240">

**Comment by MudkipBanana** [comment]
The author of this mod hasn't been active since February. I don't know much about it being truly safe or not, but good job!

**Comment by Metabolix** [comment]
Version 2.0.0 converts images during install. I think it's a better approach, because any extra code in the boot loader stage (with full access to the computer HW, firmware, disks and all) can cause unexpected and terrible problems.

**Comment by FREEWING-JP** [comment]
> Version 2.0.0 converts images during install.

But BMP file format is Very FAT .
BMP files waste space on EFI .

> any extra code in the boot loader stage

I think so . 
But There are no special characteristics to be concerned about in the program code that expands compressed images .

**Comment by Metabolix** [comment]
> But There are no special characteristics to be concerned about in the program code that expands compressed images .

Buffer overflows are very common in decoding and decompression implementations. For example, the [upng](https://github.com/elanthis/upng) library (which you apparently used) warns that "Several potential buffer overflows in the original source have been fixed in uPNG, but there may be more. Do NOT use uPNG to load data from untrusted sources, e.g. the Web. Doing so may open a remotely exploitable buffer overflow attack in your application."

Also, many of these tiny libraries support only a limited set of features, so some images would still need to be re-encoded.

I'm not convinced about upng or picojpeg for this project.

**Comment by FREEWING-JP** [comment]
> Buffer overflows are very common in decoding and decompression implementations.

Okay . I finally understood .
