### ISSUE TITLE
Mein Computer startet wegen HackBGRT nicht mehr

### ISSUE THREAD

**Issue by sonnyregnidiki** [Metabolix/HackBGRT#68]
my computer doesn't start anymore because of HackBGRT.  I installed HackBGRT, after a while I wanted to uninstall it and deleted the folder a: / Boot / EFI / HackBGRT.  now my computer always starts with an error message that cannot be skipped.  what can i do if i don't want to reset my computer?  By the way, I have an Ubuntu CD.

**Comment by sonnyregnidiki** [comment]
My Email is lauritz6000000@gmail.com .

**Comment by sonnyregnidiki** [comment]
I read that it is at your own risk but I ask for an answer anyway..

**Comment by sonnyregnidiki** [comment]
![1609847392112560605516964759275](https://user-images.githubusercontent.com/74065859/103643202-90326100-4f54-11eb-8556-df53cecfabbb.jpg)

**Comment by sonnyregnidiki** [comment]
HackBGRT: Failed to load configuration (\EFT VlackBGRT\config.txt) 1 HackBGRT: No config. no command line HackBGRT has failed. Use parameter debug=1 for details. Get a Windows Install disk or a recovery disk to fix your boot.
HackBGRT version: v1.5.1
Press any key to exit.

**Comment by sonnyregnidiki** [comment]
I can access my hard drive from Ubuntu

**Comment by Metabolix** [comment]
> my computer doesn't start anymore because of HackBGRT.

That's not true. Your computer doesn't start anymore because *you manually deleted boot files*. HackBGRT setup has an option for uninstalling, and if you had used that, you wouldn't have this problem. 

Your screenshot clearly tells you what to do: "Get a Windows Install disk or a recovery disk to fix your boot."

Just to repeat: You need to restore `\EFI\Microsoft\Boot\bootmgfw.efi` from a backup of from web, or you can use Windows installation media to fix boot issues, like the message says.
