### ISSUE TITLE
installer finishes successfully but boot logo doesn't change

### ISSUE THREAD

**Issue by OrangeTurtle197** [Metabolix/HackBGRT#72]
i replaced the provided bmp file with my own file in the unzipped folder then successfully ran the installer script, but it didn't change the boot logo.

**Comment by chenjj100419** [comment]
Me too

**Comment by deezdrama** [comment]
Me too, went through all the damn trouble of reformating windows so I could run UEFI just to change my damn boot logo because its going on an arcade machine and it didnt do a damn thing. If its not compatible with current windows version then that needs to be made public on the download page. Wasted a whole day for nothing.

**Comment by schm1dtHL** [comment]
It's likely that you've all got older machines that do not handle UEFI correctly, and which will just run bootx64.efi rather than the one denoted in the boot entry, which HackBGRT doesn't handle right now from my testing of it The best solution for it right now is to forcibly take the custom EFI file from HackBGRT and replace bootx64.efi with it in the EFI System Partition.

**Comment by OrangeTurtle197** [comment]
works fine now
