### ISSUE TITLE
Doesn't work on HP laptop

### ISSUE THREAD

**Issue by NERDBUG96** [Metabolix/HackBGRT#77]
(yes, I'm aware this is similar to other issues, just not identical.)
I am trying to install HackBGRT on my HP laptop.  The setup runs fine while following this guide: https://www.youtube.com/watch?v=a9B9eJnKBtY, and I have secure boot disabled and everything, but when I restart I get the HP logo.  What I really find weird is that it worked about 4-6 months ago with my original copy of windows (had to reinstall, due to corruption that windows apparently couldn't fix :( ), but won't work with my new copy, which is 20H2, if that matters.  Any help is appreciated.

**Comment by WesternGamer** [comment]
I am not a developer for this project on github but I had the same problem after my HP laptop updated. I fixed my problem by completely uninstalling HackBGRT then reinstalling it.

**Comment by Metabolix** [comment]
Please try the new release, first do a complete uninstall and then reinstall the new version.

**Comment by migue802** [comment]
Hey @Metabolix, this is an issue for me too in Windows 11, this might be useful info:
System Model: HP Pavilion x360 Convertible 14-cd0xxx
OS Version: 10.0.22621 compilation 22621

Tried both normal installation and alternative installation, they say it's succesful, but HP default logo still shows. Let me know if you need more debug info.

**Comment by Metabolix** [comment]
Closing bugs from obsolete versions. Please reopen if this is still valid for the most recent version.

**Comment by migue802** [comment]
The issue still persists with both regular installation and alternative installation. Legacy works fine.

System Model: HP Pavilion x360 Convertible 14-cd0xxx
OS: Windows 11
OS Version: 10.0.22621 compilation 22621

> Tried both normal installation and alternative installation, they say it's succesful, but HP default logo still shows. Let me know if you need more debug info.

**Comment by Metabolix** [comment]
@migue802 Technically you should open a new issue, because in this year 2021 issue, the problem happened with the Legacy installation method (which was the only choice back then). For debug information, please first remove HackBGRT, then for each of the three installation methods, try install, reboot, uninstall, and finally include the `setup.log` in your report to get the most feedback on what goes wrong. Some machines just seem to resist changes to boot loader list (BootOrder) and if that's the case, I don't really know how to debug that remotely.
