### ISSUE TITLE
Failed to load up config

### ISSUE THREAD

**Issue by EightSomething** [Metabolix/HackBGRT#86]
Anybody help me please i cant bootup windows anymore
![16371103566951794704561](https://user-images.githubusercontent.com/92574007/142089518-ab253f1d-0fa5-455e-9551-3fc964d7e23e.jpg)

**Comment by slowblade986** [comment]
SAME
DID YOU FIX IT

**Comment by LeBazarDeBryan** [comment]
Do you have Secure Boot disabled before doing this ?

For Windows you can install it with <a href="https://github.com/pbatard/rufus/releases/latest">Rufus</a> with a <a href="https://dl.malwarewatch.org/windows/">Windows ISO</a>.

**Comment by Metabolix** [comment]
This is a really strange situation. Does this happen with version 2.0.0 as well? (It's also safer to use since it should have a better fallback to the original boot loader.) If it does, more information about the disk partition layout would be appreciated (for example, Disk Management app or `diskpart` tool), along with the `setup.log` from the installation.

**Comment by Metabolix** [comment]
Closing bugs from obsolete versions. Please reopen if this is still valid for the most recent version.
